ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"

[[ -f ~/.config/X11/Xresources ]] && xrdb -merge ~/.config/X11/Xresources

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

xset -b
xset r rate 200 50
xset s off
xset -dpms

exec i3
