theme = "horizon"

[editor]
auto-format = false
color-modes = true
bufferline = "always"

[editor.statusline]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator" ]

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "␣"
nnbsp = "␣"
tab = "→"
tabpad = " "

[editor.indent-guides]
render = true
character = "┊"
skip-levels = 0

[keys.normal]
"C-/" = "toggle_comments"
esc = [ "collapse_selection", "keep_primary_selection" ]
# Move selection up/down (clobbers the default register!)
A-k = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
A-j = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]

[keys.normal.Z]
Z = ":write-quit-all"
Q = ":quit-all"

[keys.normal.C-w]
c = "wclose"

[keys.select]
"C-/" = "toggle_comments"
