# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Don't save duplicate lines or lines starting with space
HISTCONTROL=ignoreboth:erasedups

# Don't limit size of the history file
HISTSIZE=
HISTFILESIZE=

# Bash behaviour
shopt -s histappend # Append to history file
shopt -s autocd     # cd into dirs without explicit cd command
shopt -s cdspell    # Autocorrect cd names
shopt -s dirspell   # Autocorrect dir names
shopt -s globstar   # Enable '**' glob
shopt -s checkwinsize

# Bash completion
if [ -f /usr/share/bash_completion/bash_completion ]; then
  source /usr/share/bash_completion/bash_completion
fi

#
# # ex - archive extractor
# # usage: ex <file>
ex () {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1   ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

# Turn on tab and shift+tab completion
bind    'TAB':menu-complete
bind '"\e[Z"':menu-complete-backward

# Terminal tput color codes
export FGBlack=$(tput setaf 0)
export FGRed=$(tput setaf 1)
export FGGreen=$(tput setaf 2)
export FGYellow=$(tput setaf 3)
export FGBlue=$(tput setaf 4)
export FGMagenta=$(tput setaf 5)
export FGCyan=$(tput setaf 6)
export FGWhite=$(tput setaf 7)

export BGBlack=$(tput setab 0)
export BGRed=$(tput setab 1)
export BGGreen=$(tput setab 2)
export BGYellow=$(tput setab 3)
export BGBlue=$(tput setab 4)
export BGMagenta=$(tput setab 5)
export BGCyan=$(tput setab 6)
export BGWhite=$(tput setab 7)

export FBGReset=$(tput sgr0)

# Source git prompt
if [ -f /usr/share/git/completion/git-prompt.sh ]; then
  source /usr/share/git/completion/git-prompt.sh
fi

function errcode () {
  local status=$?
  [ $status != 0 ] && echo -n "$status "
}

export PS1='\[$FGRed\]$(errcode)\[$FGBlue\]\w\[$FGMagenta\]$(__git_ps1) \[$FBGReset\]\$ '
export PATH=$HOME/scripts:$PATH

# Less config
export LESS_TERMCAP_mb=$FGMagenta # begin bold
export LESS_TERMCAP_md=$FGRed     # begin blink
export LESS_TERMCAP_so=$FGBlue    # begin reverse video
export LESS_TERMCAP_us=$FGYellow  # begin underline
export LESS_TERMCAP_me=$FBGReset  # reset bold/blink
export LESS_TERMCAP_se=$FBGReset  # reset reverse video
export LESS_TERMCAP_ue=$FBGReset  # reset underline

export MANPAGER='less -s -M +Gg'

# Aliases
alias ls='ls -hN --color=auto --group-directories-first'
alias tree='tree -C --dirsfirst'
alias ll='ls -Ao'
alias la='ls -A'
alias grep='grep --color=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias mkdir='mkdir -pv'
alias cp='cp -i'
alias rm='rm -i'
alias mv='mv -i'
alias df='df -h'
alias free='free -m'
alias cal='cal -m'
alias vim='nvim'
alias sigma="ssh sigma.ug.edu.pl -l gchojnacki"

export CHROME_BIN=/bin/brave
