#!/bin/bash
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

##################
# Bash behaviour #
##################

# Shopts
shopt -s histappend # Append to history file
shopt -s autocd     # cd into dirs without explicit cd command
shopt -s cdspell    # Autocorrect cd names
shopt -s dirspell   # Autocorrect dir names
shopt -s globstar   # Enable '**' glob
shopt -s checkwinsize

# Enable tab and shift+tab completion
bind 'TAB':menu-complete
bind '"\e[Z"':menu-complete-backward

# Append commands to history immediately
PROMPT_COMMAND="history -a;$PROMPT_COMMAND"

# Don't save duplicate lines or lines starting with space
HISTCONTROL=ignoreboth:erasedups

# Don't limit size of the history file
HISTSIZE=
HISTFILESIZE=

# FZF's shell additions
[ -f /usr/share/fzf/key-bindings.bash ] && source /usr/share/fzf/key-bindings.bash
[ -f /usr/share/fzf/completion.bash ] && source /usr/share/fzf/completion.bash

# ex - archive extractor
# usage: ex <file>
function ex () {
  if [ -f "$1" ]; then
    case "$1" in
      *.tar.bz2) tar xjf    "$1";;
      *.tar.gz)  tar xzf    "$1";;
      *.bz2)     bunzip2    "$1";;
      *.rar)     unrar x    "$1";;
      *.gz)      gunzip     "$1";;
      *.tar)     tar xf     "$1";;
      *.tbz2)    tar xjf    "$1";;
      *.tgz)     tar xzf    "$1";;
      *.zip)     unzip      "$1";;
      *.Z)       uncompress "$1";;
      *.7z)      7z x       "$1";;
      *) echo "'$1' cannot be extracted via ex()";;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}


function tomp3() {
  ffmpeg -i "$1" "${1}.mp3"
}

# venv - simplify python virtual environments
# usage: venv <command>
function venv() {
  function usage() {
    echo -e 'usage: venv <command>\n'
    echo -e 'Streamline usage of python virtual environments\n'
    echo -e 'Available commands:'
    echo -e '  init   initialize venv in the current directory'
    echo -e '  start  activate venv in the current directory'
    echo -e '  end    deactivate the current venv\n'
  }

  case $1 in
    'init')
      if [ ! -d ./venv ]; then python -m venv ./venv
      else echo 'venv already exists in this directory'; fi ;;
    'start')
      if [ -f ./venv/bin/activate ]; then source ./venv/bin/activate
      else echo 'No venv in the current directory'; fi ;;
    'end')
      if [[ $(type -t deactivate) == function ]]; then deactivate
      else echo 'Cannot deactivate venv'; fi ;;
    *) usage ;;
  esac
}

#################
# Prompt config #
#################
function errcode () {
  local status=$?
  [ $status != 0 ] && echo -n " $status!"
}

if [ -f /usr/share/git/completion/git-prompt.sh ]; then
  source /usr/share/git/completion/git-prompt.sh
fi

export PS1='\[$T4\]\w\[$T5\]$(__git_ps1)\[$T1\]$(errcode)\[$TR\] \$ '
export PS4='# '
export PATH="$HOME/scripts:$PATH"

###########
# Aliases #
###########
alias ls='ls -hN --color=auto --group-directories-first'
alias tree='tree -C --dirsfirst'
alias ll='ls -Ao'
alias la='ls -A'
alias grep='grep --color=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias mkdir='mkdir -pv'
alias cp='cp -iv'
alias rm='rm -Iv'
alias mv='mv -iv'
alias df='df -h'
alias free='free -h'

alias v="$EDITOR"
alias sudo="sudo -E"
alias sv='sudoedit'
alias e='ranger'
alias f='fff'
alias o='xdg-open'
alias cal='cal -m'
alias mpvf='mpv "$(fzf)"'
alias legendary='/opt/Heroic/resources/app.asar.unpacked/build/bin/linux/legendary'
alias hex='od -v -tx1z'
