#!/bin/bash
# If not running interactively, don't do anything
[[ $- != *i* ]] && return

##################
# Bash behaviour #
##################

# Shopts
shopt -s histappend # Append to history file
shopt -s autocd     # cd into dirs without explicit cd command
shopt -s cdspell    # Autocorrect cd names
shopt -s dirspell   # Autocorrect dir names
shopt -s globstar   # Enable '**' glob
shopt -s checkwinsize

# Enable tab and shift+tab completion
bind 'TAB':menu-complete
bind '"\e[Z"':menu-complete-backward

# Don't save duplicate lines or lines starting with space
HISTCONTROL=ignoreboth:erasedups

# Don't limit size of the history file
HISTSIZE=
HISTFILESIZE=

##############
# TTY Colors #
##############

if [ "$TERM" = "linux" ]; then
    echo -en "\e]P7BBBBBB" # Lightgrey
    echo -en "\e]PFD5D8DA" # White
    echo -en "\e]P016161C" # Black
    echo -en "\e]P84C4D53" # Darkgrey
    echo -en "\e]P1E95678" # Darkred
    echo -en "\e]P9E95678" # Red
    echo -en "\e]P2F09483" # Darkgreen
    echo -en "\e]PAF09483" # Green
    echo -en "\e]P4FAB795" # Darkblue
    echo -en "\e]PCFAB795" # Blue
    echo -en "\e]P3FAC29A" # Brown
    echo -en "\e]PBFAC29A" # Yellow
    echo -en "\e]P625B0BC" # Darkcyan
    echo -en "\e]PE25B0BC" # Cyan
    echo -en "\e]P5B877DB" # Darkmagenta
    echo -en "\e]PDB877DB" # Magenta
    clear # For background artifacting
fi

#############
# Variables #
#############

# Terminal tput color codes
export FGBlack=$(tput setaf 0)
export FGRed=$(tput setaf 1)
export FGGreen=$(tput setaf 2)
export FGYellow=$(tput setaf 3)
export FGBlue=$(tput setaf 4)
export FGMagenta=$(tput setaf 5)
export FGCyan=$(tput setaf 6)
export FGWhite=$(tput setaf 7)

export BGBlack=$(tput setab 0)
export BGRed=$(tput setab 1)
export BGGreen=$(tput setab 2)
export BGYellow=$(tput setab 3)
export BGBlue=$(tput setab 4)
export BGMagenta=$(tput setab 5)
export BGCyan=$(tput setab 6)
export BGWhite=$(tput setab 7)

export FBGReset=$(tput sgr0)

# Environmental variables
export MANPAGER='less -s -M +Gg'
export EDITOR='nvim'
export TERMINAL='alacritty'
export CHROME_BIN='/bin/brave'
export FZF_DEFAULT_OPTS='--color 16'

#############
# Utilities #
#############

# Source bash completion
if [ -f /usr/share/bash_completion/bash_completion ]; then
  source /usr/share/bash_completion/bash_completion
fi

# Source git prompt
if [ -f /usr/share/git/completion/git-prompt.sh ]; then
  source /usr/share/git/completion/git-prompt.sh
fi

# ex - archive extractor
# usage: ex <file>
function ex () {
  if [ -f "$1" ]; then
    case "$1" in
      *.tar.bz2) tar xjf    "$1";;
      *.tar.gz)  tar xzf    "$1";;
      *.bz2)     bunzip2    "$1";;
      *.rar)     unrar x    "$1";;
      *.gz)      gunzip     "$1";;
      *.tar)     tar xf     "$1";;
      *.tbz2)    tar xjf    "$1";;
      *.tgz)     tar xzf    "$1";;
      *.zip)     unzip      "$1";;
      *.Z)       uncompress "$1";;
      *.7z)      7z x       "$1";;
      *) echo "'$1' cannot be extracted via ex()";;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}


#################
# Prompt config #
#################
function errcode () {
  local status=$?
  [ $status != 0 ] && echo -n "$status "
}

export PS1='\[$FGRed\]$(errcode)\[$FGBlue\]\w\[$FGMagenta\]$(__git_ps1) \[$FBGReset\]\$ '
export PS4='# '
export PATH=$HOME/scripts:$PATH


###############
# Less config #
###############
export LESS_TERMCAP_mb=$FGMagenta # Begin bold
export LESS_TERMCAP_md=$FGRed     # Begin blink
export LESS_TERMCAP_so=$FGBlue    # Begin reverse video
export LESS_TERMCAP_us=$FGYellow  # Begin underline
export LESS_TERMCAP_me=$FBGReset  # Reset bold/blink
export LESS_TERMCAP_se=$FBGReset  # Reset reverse video
export LESS_TERMCAP_ue=$FBGReset  # Reset underline

###########
# Aliases #
###########
alias ls='ls -hN --color=auto --group-directories-first'
alias tree='tree -C --dirsfirst'
alias ll='ls -Ao'
alias la='ls -A'
alias grep='grep --color=auto'
alias egrep='egrep --colour=auto'
alias fgrep='fgrep --colour=auto'
alias mkdir='mkdir -pv'
alias cp='cp -iv'
alias rm='rm -iv'
alias mv='mv -iv'
alias df='df -h'
alias free='free -h'
alias cal='cal -m'
alias vim='nvim'
alias timer="termdown"
